### ISSUE TITLE
希望能够增加端口配置选项

### ISSUE THREAD

**Issue by wingser** [semicons/java_oci_manage#10]
我想用云服务器（容器）启动r探长，但是启动后，云主机会把我内网配置的9527映射到外网变成一个新的端口。这种情况下，虽然服务启动了，但是机器人使用默认的9527链接服务，就链接不上了。如果能够手动配置一个端口，让机器人连接，就完美了。

如果能同时配置URL和端口，那阿里云IDE都可以上了。非常完美。不止作者是否方便添加对应功能。

**Comment by semicons** [comment]
自己看文档
