### ISSUE TITLE
更新3.7.0后启动失败

### ISSUE THREAD

**Issue by cantona97** [semicons/java_oci_manage#11]
两台机子都是从上一版更新，更新后启动提示：
端口检测结果：未开放
检测到您没有打开端口，正在尝试打开本机端口。。。
端口打开失败！请确认云面板防火墙是否放开并尝试是否可以操作bot。

**Comment by cantona97** [comment]
服务器段提示未放开，实际测试可用

**Comment by semicons** [comment]
以能访问为主
