### ISSUE TITLE
程序错误🥺🥺，错误信息为：oracle配置获取成功,但当前配置获取可用域报错,疑似被封或密钥错误请检查：

### ISSUE THREAD

**Issue by zhoushao2018** [semicons/java_oci_manage#12]
机子换过了还是同样问题，密匙换了好几次，一直解决不了不知道咋回事
点客户端负载还出现信息但是点别的就直接报错了，账号没有被封登上去一切正常，机器人IP也看到了，求大佬看看咋回事

![image](https://user-images.githubusercontent.com/63604074/212436009-7ddf8db5-c20e-4a0e-bf22-533f9c589740.png)
![image](https://user-images.githubusercontent.com/63604074/212436052-7ae872bd-c1d3-4b54-9d4c-f120c2a6a6cc.png)

**Comment by zhoushao2018** [comment]
三十天试用期已过 ，但提示就这样

**Comment by fulinkapp** [comment]
我也跑不起来。
java.lang.RuntimeException,message:🥺🥺首次运行出错，请检查异常日志：Error returned by LaunchInstance operation in Compute service.(400, InvalidParameter, false) Invalid shape config

**Comment by zhoushao2018** [comment]
> 我也跑不起来。 java.lang.RuntimeException,message:🥺🥺首次运行出错，请检查异常日志：Error returned by LaunchInstance operation in Compute service.(400, InvalidParameter, false) Invalid shape config

蓝瘦啊 怎么就咱俩出这事

**Comment by semicons** [comment]
看看你的秘钥文件和配置是否匹配 或者程序读不到你的文件 （是否在root目录

**Comment by zhoushao2018** [comment]
> 看看你的秘钥文件和配置是否匹配 或者程序读不到你的文件 （是否在root目录

感谢大佬，一语惊醒梦中人
仔细检查了一下是复制配置文件错了，
 是我电脑复制粘贴有问题然后才会这样子[电脑问题](https://www.nodeseek.com/post-927-1)，修改后机器人已经可以操作]
