### ISSUE TITLE
debian10 如何安装openjdk-17-jdk

### ISSUE THREAD

**Issue by hyy34** [semicons/java_oci_manage#17]
google了下，感觉不支持呢？请问如何安装呢？

apt install openjdk-17-jdk

源里没有呢。

**Comment by hyy34** [comment]
找到了。
下载jdk17：
wget https://download.java.net/openjdk/jdk17/ri/openjdk-17+35_linux-x64_bin.tar.gz
解压至/usr/local/文件夹：
tar xzvf openjdk-17+35_linux-x64_bin.tar.gz -C /usr/local/
设置环境变量：
export JAVA_HOME=/usr/local/jdk-17
export PATH=$PATH:$JAVA_HOME/bin

可能重启就没有了，现在还不知道如何做到开机自动加载环境变量。

**Comment by shenghuang147** [comment]
> > 找到了。 下载jdk17： `wget https://download.java.net/openjdk/jdk17/ri/openjdk-17+35_linux-x64_bin.tar.gz` 解压至/usr/local/文件夹： `tar xzvf openjdk-17+35_linux-x64_bin.tar.gz -C /usr/local/` 设置环境变量： `export JAVA_HOME=/usr/local/jdk-17` `export PATH=$PATH:$JAVA_HOME/bin`
> > 可能重启就没有了，现在还不知道如何实现开机自动加载环境指标。
> 
> ```shell
> cat > /etc/profile.d/openJDK.sh <<EOF
> export JAVA_HOME=/usr/local/jdk-17
> export PATH=\$PATH:\$JAVA_HOME/bin
> EOF
> ```
> 
> 以上命令需要root权限
> 
> 这样就行了，如果不想要这个环境变量了就直接 `rm /etc/profile.d/openJDK.sh` 就可以了

抱歉忽略了 `EOF` 使用变量会被自动解析, 已修正
