### ISSUE TITLE
不要用这个,这个狗娘养的盗刷信用卡

### ISSUE THREAD

**Issue by feix0006** [semicons/java_oci_manage#25]
大家都不要用这个,这个狗娘养的盗刷信用卡

**Comment by benname** [comment]
这把建议有病及早治疗

**Comment by semicons** [comment]
你好，难为你专门注册个号来评论，辛苦你了！

**Comment by jpmsu** [comment]
我专门跑了云查杀 https://www.virustotal.com/gui/file/ee9cd9399481c8d24c796139ca14c33afd6252e755dff829ba9b2b87d1bdead6 ，没有任何问题
