### ISSUE TITLE
选择启动盘后，无法再修改系统

### ISSUE THREAD

**Issue by Wszhdg** [semicons/java_oci_manage#29]
因为本来的启动盘系统与需要开机系统不一致导致无法开机，在网页开机时可以选择映像，但是在bot开机选择启动盘后选择系统是无效的，无法覆盖原系统，期望能帮助改进

**Comment by semicons** [comment]
甲骨文不支持覆盖系统操作，选择启动盘开机需要原有配置一样才可以，无法覆盖启动盘本身的系统，不然你的数据就被覆盖等同于新开机，选择启动盘则无意义。想重新开机可以释放掉启动盘
