### ISSUE TITLE
关于 云账户管理 等功能请教

### ISSUE THREAD

**Issue by aansheng** [semicons/java_oci_manage#3]
云账户管理（修改租户名、修改邮箱、添加管理员用户、删除用户、重置密码）

其中有一个是重置密码，是不是可以直接重置一个新密码给我登录呢？我之前绑定的域名邮箱，域名过期了，密码也丢了，现在只有OCI的API信息，账号完全登录不上去。。。。。

**Comment by semicons** [comment]
可以的
