### ISSUE TITLE
开机日志提示错误1596，求解

### ISSUE THREAD

**Issue by wlqb2001** [semicons/java_oci_manage#32]
开机日志提示错误1956，求解

![Screenshot_2024_10_14_14_52_43_22_0b342c26d6c44f3c8d2de40eabb4e1da](https://github.com/user-attachments/assets/151258c2-729b-485b-9f23-8e56816ab8b8)

**Comment by wlqb2001** [comment]
![微信截图_20241015224848](https://github.com/user-attachments/assets/1bf34df4-7179-4069-9c49-708fed413280)
![微信截图_20241015224948](https://github.com/user-attachments/assets/1423b97b-67dc-46c5-a465-264d943a7d35)

**Comment by semicons** [comment]
提示你网络连接有问题，找个网络畅通的机器部署即可
