### ISSUE TITLE
profile:DEFAULT,失败(｡•ˇ‸ˇ•｡)，错误信息为🐶: 已选择的配置没有匹配上当前选择的系统或您自定义的系统，请更换其他系统

### ISSUE THREAD

**Issue by wlqb2001** [semicons/java_oci_manage#33]
profile:DEFAULT,失败(｡•ˇ‸ˇ•｡)，错误信息为🐶:
已选择的配置没有匹配上当前选择的系统或您自定义的系统，请更换其他系统,
更换了其他系统还是提示出错

**Comment by semicons** [comment]
选择对应系统即可，arm和amd的不通用，谷歌即可

**Comment by leonadoking** [comment]
profile:DEFAULT,失败(｡•ˇ‸ˇ•｡)，错误信息为🐶:
已选择的配置没有匹配上当前选择的系统或您自定义的系统，请更换其他系统
我也是遇到同样的问题，我不管选择Ubuntu20还是Centos，都报错，我也自定义了系统，但还是报错，
请问上面提到的谷歌即可，是什么意思 。 
那选择哪个系统呢？

麻烦解答下，万分感谢。

<img width="431" height="308" alt="Image" src="https://github.com/user-attachments/assets/addd6888-a610-45cc-a239-be71c31613a4" />
