### ISSUE TITLE
服务器端口开启成功，TG无法识别

### ISSUE THREAD

**Issue by zzj6666** [semicons/java_oci_manage#5]
![image](https://user-images.githubusercontent.com/101039599/177103921-f6110ea6-1192-483d-ac0d-d7f4e1a53f3b.png)
![image](https://user-images.githubusercontent.com/101039599/177103985-ba8a0edb-2875-4791-b0d1-33faca0bfec0.png)

**Comment by semicons** [comment]
port.ping.pe检查你的端口
