### ISSUE TITLE
大佬我之前的机子删鸡我重新开了个搭建好了也连接了但是里面的数据还是之前机子的无法使用

### ISSUE THREAD

**Issue by lunhui11** [semicons/java_oci_manage#7]
弄好了有个这个   非闪电用户只能使用1个，请删除其他客户端    然后我再R探长打开里面提示的无配置，我随便点一个里面报错是之前机子的IP  请问应该怎么解决呢。org.apache.http.conn.ConnectTimeoutException: Connect to 152.67.198.228:9527 [/152.67.198.228] failed: connect timed out
重置用户信息我重置过了两次还是以旧是这个问题

**Comment by semicons** [comment]
删除其他客户端
