### ISSUE TITLE
tmux中启动机器人后，实时日志过零点不刷新

### ISSUE THREAD

**Issue by sdw4agl** [semicons/java_oci_manage#9]
大佬，23日我在tmux中启动后机器人开始刷机后，实时刷新日志中在23日23时59分之后就不会再刷新了。日志文件`log_r_client.log`记录正常，一直有数据写入，但是是从24日0时1分开始的记录的。不知是否为bug，请大佬斟情处理。

**Comment by semicons** [comment]
0点日志归档而已，需要重新查看
